GET http://localhost:5000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmVpbCIsImlhdCI6MTYxODQyNzEzMSwiZXhwIjoxNjE4NDI3MTQ2fQ.rzmKesLYb1yvpIuLvezdkmvaPQyFVnFbN988UiaQ0mk

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmVpbCIsImlhdCI6MTYxODQyNzI5OH0.rR7bUpC6KlLweKnq-8g-Yzl8DDafLQBwYmvIGbh52JA"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Neil"
} 