GET http://localhost:5000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmVpbCIsImlhdCI6MTYxODQ2NDUyNCwiZXhwIjoxNjE4NDY0NTM5fQ.48ZJ7WNu9ttHxJp9rMz6oDxFyQL7bhNvRjm74HSjSvQ


###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmVpbCIsImlhdCI6MTYxODQ2NDA5Mn0.6NZfPzHIAbf1sSR-Wa6y2GFDs-mVi5YUR-LOy5dHwSU"
}


###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmVpbCIsImlhdCI6MTYxODQ2NDA5Mn0.6NZfPzHIAbf1sSR-Wa6y2GFDs-mVi5YUR-LOy5dHwSU"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Neil"
} 

